backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "doc" # Used in routes, e.g., /admin/collections/blog
    label: "Residelia Help" # Used in the UI
    folder: ["docs", "docs/Assets", "docs/Portfolios", "docs/Data", "docs/Faqs" ] # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}